# **HDBSCAN**

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
data = pd.read_csv("/content/Social_Network_Ads.csv")

In [8]:
data.head(1)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [9]:
!pip install hdbscan
#Import the hdbscan library
import hdbscan

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 50.1 MB/s eta 0:00:00
  Attempting uninstall: cython
    Found existing installation: Cython 3.0.10
    Uninstalling Cython-3.0.10:
      Successfully uninstalled Cython-3.0.10


In [12]:
x = data.iloc[:, [2, 3]].values
y = data.iloc[:, 4].values

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [17]:
clc = hdbscan.HDBSCAN(min_cluster_size = 5, min_samples = None, algorithm = 'best', metric = 'euclidean')

In [19]:
y_pred_train = clc.fit_predict(x_train)
y_pred_test = clc.fit_predict(x_test)

In [20]:
print(y_pred_train)

[ 3  2  8  0 10  1  4 18  8 -1  6  8 -1  8  6  5  0  7 -1  8 -1  1  2  1
  8 17  4  0  2  0 -1  4  9  0 -1 17 -1  7 14  6 -1 -1 11 15 14  0 13  0
 16 12  8 12 -1 18  1 -1 11  5 15  2 18 -1  4  7  6  7  4  2  2  7 13 -1
  3 10  0  0  7 16  0 10 17  2  1  6 15 -1  9 13  0 -1  4  2  7  6  4 -1
 17  4 11 -1 17 -1  0  6  3  2  0  6  1  4 -1 10  5 -1 17 -1  6 13  8 -1
  6  5  9  6  0  9 -1 17  6  9  7 -1 -1  6 14 -1 10  7  7  6 -1 17  4 14
  0  6 13 11 12 -1  6 18  2 15 12 -1 12  6 15 -1  8  0  6 -1  0 -1 13 18
  6 -1 11 10 14  2 -1 15 -1  8 16  8 12  6  0  9  8  0  6 10  8  1  2  8
  0  5  0 -1  4 10 -1  9 11  2 -1 13 10 14 -1  6  4 12 -1 -1  8  0  2 -1
  0 18  7  9  6 14  6 -1  0 13 -1 14 -1 -1  2  8 11 17  7 16 -1 -1  6  1
 14 13  1 -1 14 10  1  9  0  4  4  3  4 14  0  0  9  6  5 -1 16  8  6 -1
  4 10 -1  8  8 -1  1 -1  1 10  5  9 -1 16  6 14  3  6 -1 16 -1 15  7  3
  7  7  0  5  8  4  8  6  4  8  8  2]


In [21]:
print(y_pred_test)

[ 2  1  3  3  1  4 -1  0 -1  1  1  1  1  3  2 -1  3  2 -1  4  1  0  1 -1
 -1  0  2  3  1  2  2  3  1  1  1  1  3  1  5  5  2  1  2  4 -1  1  3 -1
  5  2 -1  4  1 -1  2  5  2  3  4  4  4 -1  3 -1 -1  2  2  1  1 -1  0  3
  1  4  2  3  3  1  5 -1  0  2  1  5 -1  3  3  0  1  1  1  0  1  5  2 -1
  1  5 -1 -1]


In [22]:
print(clc.labels_)

[ 2  1  3  3  1  4 -1  0 -1  1  1  1  1  3  2 -1  3  2 -1  4  1  0  1 -1
 -1  0  2  3  1  2  2  3  1  1  1  1  3  1  5  5  2  1  2  4 -1  1  3 -1
  5  2 -1  4  1 -1  2  5  2  3  4  4  4 -1  3 -1 -1  2  2  1  1 -1  0  3
  1  4  2  3  3  1  5 -1  0  2  1  5 -1  3  3  0  1  1  1  0  1  5  2 -1
  1  5 -1 -1]


In [23]:
print(clc.probabilities_)

[1.         1.         0.50001125 1.         1.         1.
 0.         1.         0.         0.74999663 1.         0.99999994
 0.99999911 0.500012   1.         0.         0.500012   0.99960028
 0.         1.         0.9999995  1.         1.         0.
 0.         1.         1.         1.         1.         0.99996551
 1.         0.9999925  1.         1.         1.         1.
 0.99982455 0.74999916 1.         0.66670696 1.         1.
 0.99950592 1.         0.         1.         1.         0.
 0.66668907 0.99960028 0.         0.99999422 1.         0.
 0.99953837 1.         0.99950592 1.         0.75000467 1.
 0.75000483 0.         0.500012   0.         0.         0.99916912
 0.99965821 1.         0.99999861 0.         1.         0.500012
 0.99997995 1.         0.99973763 0.50001    0.99994001 1.
 1.         0.         1.         0.99921051 1.         1.
 0.         1.         0.50001069 0.64285829 0.59999989 1.
 0.74999991 1.         1.         1.         0.9994026  0.
 0.999982   1.    

In [24]:
print(clc.outlier_scores_)

[0.00000000e+00 1.01244818e-05 4.99988750e-01 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.42850985e-01 0.00000000e+00
 1.66670695e-01 2.50003375e-01 0.00000000e+00 5.55555509e-08
 8.88887704e-07 4.99988000e-01 0.00000000e+00 4.99996717e-01
 4.99988000e-01 3.99720212e-04 2.04081626e-08 0.00000000e+00
 4.99999625e-07 0.00000000e+00 0.00000000e+00 3.33330081e-01
 1.46246645e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 3.44947654e-05 0.00000000e+00 7.49954815e-06
 8.79840751e-05 0.00000000e+00 1.16242277e-05 3.19973122e-05
 1.75445219e-04 2.50000844e-01 0.00000000e+00 3.33293038e-01
 0.00000000e+00 0.00000000e+00 4.94084135e-04 0.00000000e+00
 2.49995808e-01 0.00000000e+00 0.00000000e+00 7.36162076e-05
 3.33310928e-01 3.99720212e-04 3.99996180e-01 5.77765003e-06
 0.00000000e+00 3.99996099e-01 4.61633949e-04 0.00000000e+00
 4.94084135e-04 0.00000000e+00 2.49995333e-01 0.00000000e+00
 2.49995169e-01 7.81990546e-06 4.99988000e-01 3.33329028e-01
 7.49990813e-06 8.308801

In [25]:
from sklearn.metrics import confusion_matrix
cm_train = confusion_matrix(y_train, y_pred_train)
cm_test = confusion_matrix(y_test, y_pred_test)

In [30]:
print(cm_train, "\n\n", cm_test)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [37  3  1  5  3 14  8 15  9 20 10  6  5  6  8 11  7  6  9  6]
 [20 25 11 11  3  4  0 15  6  3  1  6  2  1  1  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

In [31]:
from sklearn.metrics import accuracy_score
acc_train = accuracy_score(y_train, y_pred_train)
acc_test = accuracy_score(y_test, y_pred_test)

In [33]:
print(acc_train)

0.04666666666666667


In [32]:
print(acc_test)

0.02


In [34]:
from sklearn.metrics import classification_report
cr_train = classification_report(y_train, y_pred_train)
cr_test = classification_report(y_test, y_pred_test)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: Undefin

In [35]:
print (cr_train)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.11      0.02      0.03       189
           1       0.92      0.10      0.18       111
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00    

In [36]:
print (cr_test)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00        68
           1       0.07      0.06      0.07        32
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0

    accuracy                           0.02       100
   macro avg       0.01      0.01      0.01       100
weighted avg       0.02      0.02      0.02       100

