In [18]:
'''

1-> Generate the dataset:- Using make_blobs to create a sample dataset.
2-> Estimate the bandwidth:- Using estimate_bandwidth to determine the bandwidth parameter for MeanShift.
3-> Fit the MeanShift model:- Using the MeanShift algorithm to cluster the data.
4-> Visualize the results:- Plot the clusters to see the results. "choice"

'''

'\n\n1-> Generate the dataset:- Using make_blobs to create a sample dataset.\n2-> Estimate the bandwidth:- Using estimate_bandwidth to determine the bandwidth parameter for MeanShift.\n3-> Fit the MeanShift model:- Using the MeanShift algorithm to cluster the data.\n4-> Visualize the results:- Plot the clusters to see the results. "choice"\n\n'

In [19]:
import numpy as np
from sklearn.datasets import make_blobs
from sklearn.cluster import MeanShift, estimate_bandwidth

In [22]:
# Generating data samples
coordinates = [[4,10], [2,5], [1,2], [10,20], [10,15], [3,8], [5,8]]
# another_coordinate = [[1,2,4], [2,4,7], [4,0,3]]
x, _ = make_blobs(n_samples = 100, centers = coordinates, cluster_std = 0.60)

In [32]:
# Estimate bandwidth
bandwidth = estimate_bandwidth(x, quantile = 0.2, n_samples = len(x))

'''
Quantile parameter:
This parameter is between 0 and 1.
it determine the fraction of datapoint used to estimate the bandwidth, which is the radius of the neighborhood around each point.

Practical Use: Adjusting the quantile helps control the clustering algorithm's sensitivity to data scale and point density.
In essence, the quantile parameter fine-tunes how broadly or narrowly the MeanShift algorithm considers neighborhoods around
data points, affecting the resulting number of clusters.

High Quantile: Larger bandwidth, fewer clusters, as more points are grouped together.
Low Quantile: Smaller bandwidth, more clusters, as fewer points are grouped together.
'''


"\nQuantile parameter:\nThis parameter is between 0 and 1.\nit determine the fraction of datapoint used to estimate the bandwidth, which is the radius of the neighborhood around each point.\n\nPractical Use: Adjusting the quantile helps control the clustering algorithm's sensitivity to data scale and point density.\nIn essence, the quantile parameter fine-tunes how broadly or narrowly the MeanShift algorithm considers neighborhoods around\ndata points, affecting the resulting number of clusters.\n\nHigh Quantile: Larger bandwidth, fewer clusters, as more points are grouped together.\nLow Quantile: Smaller bandwidth, more clusters, as fewer points are grouped together.\n"

In [35]:
ms = MeanShift(bandwidth = bandwidth, bin_seeding = True)
ms.fit(x)

'''
Bin Seeding in MeanShift
Purpose:
Bin seeding is used to reduce the number of initial seeds (starting points for clustering) by placing
them on a grid rather than starting with every data point.

Benefits:
This can significantly speed up the clustering process, especially for large datasets, because
it reduces the number of points the algorithm needs to consider during the iterative process.
'''

labels = ms.labels_
cluster_centers = ms.cluster_centers_

In [31]:
labels_unique = np.unique(labels)
n_clusters_ = len(labels_unique)

print("number of estimated clusters : %d" % n_clusters_)

number of estimated clusters : 4


In [36]:
print("Cluster Centers:\n", cluster_centers)

Cluster Centers:
 [[ 4.10664385  8.66151044]
 [ 1.49536841  3.66583722]
 [10.07084429 14.80057729]
 [ 9.99727994 19.88728479]]


In [37]:
print("Labels:\n", labels)

Labels:
 [0 1 0 2 0 0 2 1 0 1 3 0 3 3 2 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1
 3 1 1 3 0 3 3 0 0 2 3 2 3 0 2 2 0 0 1 0 0 0 2 0 2 1 1 1 1 2 1 0 2 0 0 0 1
 0 1 0 0 2 3 3 0 3 1 3 1 1 0 2 1 0 3 0 0 0 0 0 1 2 1]


In [38]:
print("Coordinates:\n", x)

Coordinates:
 [[ 5.42396712  8.24302113]
 [ 1.64723483  2.87471551]
 [ 3.18033749  8.20608026]
 [10.10956296 15.64339517]
 [ 5.46994368 10.72330751]
 [ 3.96816237 10.22414217]
 [ 9.96016408 15.15444954]
 [ 1.9367494   4.91937636]
 [ 3.98903888  7.68911715]
 [ 2.14097215  4.9139719 ]
 [10.5298237  19.8626616 ]
 [ 4.11234364  8.32002307]
 [10.99217119 20.75629536]
 [ 9.7947207  19.67405341]
 [10.47365884 13.48915061]
 [ 1.56680563  1.7199574 ]
 [ 3.91435127  7.91199958]
 [ 2.77020414  4.78613267]
 [ 4.7477085   7.82492955]
 [ 3.21873201  7.50879313]
 [ 2.06914226  5.1547656 ]
 [ 4.63848081 10.24631656]
 [ 0.10596611  2.27583694]
 [ 2.67805772  5.53756729]
 [ 3.28788065  8.03277319]
 [ 2.4021781   8.11562792]
 [ 3.56064195  7.94187106]
 [ 1.75878855  4.8872283 ]
 [ 2.85818663  9.02982643]
 [ 1.65674911  1.52233712]
 [-0.36241319  2.56699324]
 [ 2.54848276  8.36052611]
 [ 0.67107142  1.0077542 ]
 [ 5.09233121  7.03013427]
 [ 4.91373661  7.59307324]
 [ 5.7621107   7.06162494]
 [ 1.5748347  

In [39]:
print("Labels Unique:\n", labels_unique)

Labels Unique:
 [0 1 2 3]
